# Generated by Django 3.2 on 2021-04-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=12, unique=True, verbose_name='Phone number')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('pasp_number', models.CharField(blank=True, max_length=255, verbose_name='Passport number')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Registered date')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='Last login date')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Courier',
                'verbose_name_plural': 'Couriers',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company name')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=32, verbose_name='Device ID')),
                ('device_model', models.CharField(max_length=255, verbose_name='Device model')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('app', models.CharField(max_length=255, verbose_name='App name')),
                ('version', models.CharField(max_length=10, verbose_name='App version')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companies', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Longitude')),
                ('created_at', models.DateField(verbose_name='Created at')),
                ('updated_at', models.DateField(verbose_name='Updated at')),
                ('data', models.CharField(blank=True, max_length=255, null=True, verbose_name='Some data')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companies', verbose_name='Company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.devices', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
