# Generated by Django 3.2 on 2021-04-18 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210418_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Courier'),
        ),
    ]
